spring.application.name=challenge1

spring.datasource.url=jdbc:mysql://localhost:3306/challenge1?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Kalaivani@123


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl_auto=update

jwt.secret=igr5nog5inngrf4mvrrfn43if43f4girgn3igj4mgf4oemg4rgi4fm3fom3g